from django import forms
from django.db import connection
from .models import Cacesso

class Home(forms.Form):
	nome= forms.CharField(max_length=100)
	numeroProcesso = forms.CharField()

class EditarDadosAcesso(forms.Form):
	utilizador= forms.CharField(max_length=100)
	password = forms.CharField()
	ConfirmarPassword = forms.CharField()

class FuncionariosForm(forms.Form):
	Nome = forms.CharField(max_length=100)
	Pseodonimo = forms.CharField(max_length=20)
	Sexo = forms.CharField(max_length=10)
	DataNascimento = forms.DateField()
	Idade = forms.CharField(max_length=50, required=False)
	CodComuna = forms.CharField(max_length=50, required=False)
	CodPai = forms.CharField(max_length=50, required=False)
	CodMae = forms.CharField(max_length=50, required=False)
	IdIdentificacao = forms.CharField()
	CodEstadoCivil = forms.CharField(max_length=10, required=False)
	NomeConjuge = forms.CharField(max_length=20, required=False)
	Residencia = forms.EmailField(max_length=200, required=False)
	Numerocasa = forms.CharField()
	Telefone = forms.CharField(max_length=50, required=False)
	NumerodeConta = forms.CharField(max_length=50, required=False)
	IDEntidadeBancaria = forms.CharField(max_length=50)
	NumeroFilhos = forms.CharField(max_length=100, required=False)
	CodGrupoSanguineo = forms.CharField(max_length=100, required=False)
	CodProfissao = forms.CharField(max_length=100, required=False)
	CodCarreira = forms.DateField(required=False)
	CodCategoria = forms.CharField(max_length=100, required=False)
	DataInicioCategoria = forms.CharField(max_length=50, required=False)
	NumeroAgente = forms.DateField(required=False)
	NumeroCIF = forms.CharField(max_length=50,required=False)
	SalarioBase = forms.DateField(required=False)
	DataIngressoFuncaoPublica = forms.DateField(required=False)
	DataInicioFuncaoPublica = forms.DateField(required=False)
	DataInicioFuncaoNaEscola = forms.DateField(required=False)
	CodFuncao = forms.CharField()
	DataNomeacao = forms.CharField()
	NumeroDRN = forms.CharField(max_length=20,required=False)
	Serie=forms.DateField(required=False)
	Transferido=forms.DateField(required=False)
	CodLocalServicoAnterior=forms.DateField(required=False)
	DataTransferencia=forms.DateField(required=False)
	PorOrdemde=forms.DateField(required=False)
	OutrosLocais=forms.DateField(required=False)
	ServicoMilitar=forms.DateField(required=False)
	DataIncorporacao=forms.DateField(required=False)
	DataDesmobilizacao=forms.DateField(required=False)
	NumeroDocumento=forms.DateField(required=False)
	Codtalao=forms.DateField(required=False)
	CodHabilitacoesliterareas=forms.DateField(required=False)
	CodAnoConclusao=forms.DateField(required=False)
	CodInstituicao=forms.DateField(required=False)
	CodEspecialidade=forms.DateField(required=False)
	CodHabilitacoesProfissionais=forms.DateField(required=False)
	CodAnoConclusao2=forms.DateField(required=False)
	CodInstituicao2=forms.DateField(required=False)
	ExperienciaPratica=forms.DateField(required=False)
	Observacoes=forms.DateField(required=False)
	Fotografia=forms.ImageField(label='Seleccionar imagem', required=False)
	DataInsercao=forms.DateField(required=False)
